### ISSUE TITLE
Issue on dissipative post processing

### ISSUE THREAD

**Issue by sleepyeye** [neuraloperator/markov_neural_operator#2]
Hello.

I am a little bit confused since the implemented dissipative post processing is a little bit different from the Eq.8 in the paper. 
https://github.com/neuraloperator/markov_neural_operator/blob/67e77ed04f3909b71bb7654be2944b353bcaf227/dissipative_utils.py#L44-L45C14

Isn't it supposed to be
```python
def part_unity_post_process(x, model, rho, diss):
    return rho(torch.norm(x)) * model(x).reshape(x.shape[0],) + (1 - rho(torch.norm(x))) * diss(x)
```

not this?
```python
def part_unity_post_process(x, model, rho, diss):
    return rho(torch.norm(x)) * model(x).reshape(x.shape[0],) + (1 - rho(x)) * diss(x)
```

I'm not sure this is a bug or intended behavior so I left the issue.

**Comment by mliuschi** [comment]
Hi @sleepyeye, thanks for catching this! Yes, this is a bug. I've addressed it in [this commit](https://github.com/neuraloperator/markov_neural_operator/commit/0a30a15b8f9fb0cd81e2445ca6258be03871266b).

**Comment by sleepyeye** [comment]
Thanks @mliuschi
